services:
  wordpress:
    image: waq3/wp:latest-php8.3
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      SERVER_NAME: ${SERVER_NAME:-waq3.net:80}
      WORDPRESS_DB_HOST: ${DB_HOST:-db}
      WORDPRESS_DB_USER: ${DB_USER:-exampleuser}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD:-examplepass}
      WORDPRESS_DB_NAME: ${DB_NAME:-exampledb}
      WORDPRESS_DEBUG: ${WP_DEBUG:-0}
      WORDPRESS_TABLE_PREFIX: ${DB_TABLE_PREFIX:-wp_}
      WP_REDIS_HOST: ${WP_REDIS_CACHE_HOST:-redis}
      WP_REDIS_PORT: ${WP_REDIS_CACHE_PORT:-6379}
      CACHE_LOC: ${CACHE_LOC:-/var/www/html/wp-content/cache}
      TTL: ${TTL:-80000}
      PURGE_PATH: ${PURGE_PATH:-/__cache/purge}
      PURGE_KEY: ${PURGE_KEY:-}
      BYPASS_HOME: ${BYPASS_HOME:-false}
      BYPASS_PATH_PREFIXES: ${BYPASS_PATH_PREFIXES:-/wp-admin,/wp-content,/wp-includes,/wp-json,/feed}
      CACHE_RESPONSE_CODES: ${CACHE_RESPONSE_CODES:-000}
      CADDY_GLOBAL_OPTIONS: |
        email ${CADDY_ADMIN_EMAIL:-admin@waq3.net}
      WORDPRESS_CONFIG_EXTRA: |
        define( 'FS_METHOD', 'direct' );
        define( 'WP_CACHE', true );
        define( 'WP_SITEURL', '${WP_SITEURL:-https://waq3.net}' );
        define( 'WP_HOME', '${WP_HOME:-https://waq3.net}' );
        define( 'WP_REDIS_HOST', getenv_docker('WP_REDIS_HOST', 'redis') );
        define( 'WP_REDIS_PORT', getenv_docker('WP_REDIS_PORT', 6379) );
    volumes:
      - ./wp-content:/var/www/html/wp-content:rw
    depends_on:
      - db
      - redis
    tty: true

  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME:-exampledb}
      MYSQL_USER: ${DB_USER:-exampleuser}
      MYSQL_PASSWORD: ${DB_PASSWORD:-examplepass}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-examplepass}
    volumes:
      - ./db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - ${LOCAL_PHPMYADMIN_PORT:-8086}:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-examplepass}
    depends_on:
      - db

  redis:
    image: redis:latest
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
    command: ["redis-server"]

volumes:
  dbwp:
